### PR TITLE
Fix missing background color.

### PR DESCRIPTION
**Pull request by kiddten**
Fix for https://github.com/lektor/lektor-markdown-highlighter/issues/2

### CODE REVIEW

**Comment by fmartingr** [comment]
👍

**Comment by ericmjl** [comment]
Pinging - will it be merged?

**Comment by nixjdm** [comment]
Thanks for the ping. I tested and it works. lgtm.

**Comment by javierdebug** [comment]
Hey, I'm not getting the background color for code blocks. I select style one-dark but this is the output I'm getting in the page:

image

I can confirm the 'hll' class is present in the code but don't know what's happening with the background

**Pull request merged**
