### PR TITLE
Document that config file must exist

### LINKED ISSUE #7: pygments.css gets pruned
If I perform a clean build, Lektor does the following:
```
$ lektor build
Started build
U index.html
U static/pygments.css
[...]
Finished build in 0.75 sec
Started prune
D static/pygments.css
Finished prune in 0.02 sec
```
So it inserts the Pygments style sheet in the build output, but then later removes it again. Maybe the plugin is not registering ownership of the file and therefore Lektor decides it is a left-over old file and decides to remove it?

When testing interactively I can work around it by refreshing the build from the Lektor UI, but that is not an option when building non-interactively.

I'm using version 0.2 of the plugin because of issue #6, but I don't think the commits between 0.2 and 0.3 would make any difference.

### PR DESCRIPTION
**Pull request by mthuurne**
Documented how the stylesheet pruning can be avoided.

Fixes #7.

### CODE REVIEW

**Comment by runfalk** [comment]
Thank you for the commit!

Have you investigated if it is possible to change the source to be the plugin itself? I think it would be more obvious if a configuration file was not required. If that is not a possibility I am happy to merge this.

**Comment by nixjdm** [comment]
I agree that this *should* work without a config, but it currently is required. I've done some investigating and this can be properly fixed, but not trivially. I'm fine with this for now as a stop-gap, so I'll pull it.

To fix this we'd need to either be able to create a default artifact when a given source is gone or doesn't exist (preferred), or to create an artifact with no source explicitly and "track" the config from within the plugin's code. Neither of these is trivial. I think the latter can be done within this plugin, but the former (and I think better option) can't be done right now without changes in core. This made me discover a related bug in core I'll post soon. The [docs here](https://www.getlektor.com/docs/api/build/context/sub-artifact/) are wrong in that you can't currently create a sub_artifact with no `sources`.

**Comment by mthuurne** [comment]
Would it be an option for the plugin to create the config file if it doesn't exist?

**Comment by runfalk** [comment]
@mthuurne, we started a discussion regarding that here: https://github.com/lektor/lektor/issues/633

**Pull request merged**
